name: Run Node.js Tests

on: [push] 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test








  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/my-node-app"

# What secrets do you need to set?
# Go to your GitHub repo → Settings → Secrets and variables → Actions → Add these secrets:

# SERVER_HOST→ e.g.,ec2-13-58-99-123.compute-1.amazonaws.com

# SERVER_USER→ e.g.,ubuntu

# SERVER_SSH_KEY → your private SSH key (contents of ~/.ssh/id_rsa, no passphrase)

